name: CI

on:
  push:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build --configuration Release 

      - name: Pack
        run: dotnet pack --configuration Release
